"""Reproduce line-first examples and bounded independent naming checks.

The production checker does not search color assignments. Exhaustive finite
INPUT checks below are only a test oracle; they are never called by it.
Run: python scripts/validate_line_names.py --output outputs/line-names-2026-09-07.json
"""

from argparse import ArgumentParser
from collections import Counter
from dataclasses import asdict
from itertools import product
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from fourcolor.embedding import PlaneMap
from fourcolor.examples import dangling_triangle_map, tetrahedron_map, triangle_map
from fourcolor.line_names import audit_line_names, branch_right, canonical_line_names


def parallel_five():
    """Five parallel arcs form five distinct side spaces, including outside."""
    return PlaneMap((("A", "B"),) * 5,
                    {"A": (0, 2, 4, 6, 8), "B": (9, 7, 5, 3, 1)})


def independent_status(plane_map, flat_names):
    """Face-based oracle, intentionally separate from the line-first algorithm."""
    values = [{flat_names[d] for d in boundary if flat_names[d] is not None}
              for boundary in plane_map.faces]
    if any(len(side) > 1 for side in values):
        return "conflict"
    for edge in range(len(plane_map.edges)):
        left, right = plane_map.shores(edge)
        if left != right and values[left] and values[left] == values[right]:
            return "conflict"
    return "underdetermined" if any(not side for side in values) else "consistent"


def bounded_checks():
    """Exhaust all partial A/B names on two small maps; full A/B on two more."""
    cases = (("triangle_partial", triangle_map(), (None, "A", "B")),
             ("dangling_triangle_partial", dangling_triangle_map(), (None, "A", "B")),
             ("tetrahedron_full_two_symbols", tetrahedron_map(), ("A", "B")),
             ("five_parallel_full_two_symbols", parallel_five(), ("A", "B")))
    reports = []
    for name, plane_map, alphabet in cases:
        counts = Counter()
        for flat in product(alphabet, repeat=2 * len(plane_map.edges)):
            pairs = tuple(zip(flat[::2], flat[1::2]))
            result = audit_line_names(tuple(plane_map.rotation.values()), pairs)
            if result.status != independent_status(plane_map, flat):
                raise AssertionError(f"line/face oracle mismatch in {name}: {pairs}")
            # Propagation must be idempotent, including unspecified symbols.
            repeated = audit_line_names(tuple(plane_map.rotation.values()), result.names)
            if repeated != result:
                raise AssertionError(f"non-idempotent propagation in {name}")
            counts[result.status] += 1
        reports.append({"case": name, "alphabet": alphabet,
                        "input_assignments_checked": sum(counts.values()),
                        "outcomes": dict(sorted(counts.items())), "oracle_agreement": True})
    return reports


def main():
    """Write a deterministic report, without machine paths or hidden randomness."""
    parser = ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "outputs" / "line-names-2026-09-07.json")
    args = parser.parse_args()
    triangle = tuple(triangle_map().rotation.values())
    # These are edge names supplied directly, not generated by a coloring solver.
    good = (("A", "B"), (None, None), (None, "B"))
    bad = (("A", "B"), ("A", "B"), ("A", "C"))
    five_names = (("A", "B"), ("C", "A"), ("D", "C"), ("E", "D"), ("B", "E"))
    five_result = audit_line_names(tuple(parallel_five().rotation.values()), five_names)
    if five_result.status != "consistent":
        raise AssertionError("five-symbol naming witness is not consistent")
    report = {
        "schema_version": 1,
        "scope": "Line-first symbolic consistency only, not a four-color selection algorithm or novelty proof.",
        "randomness": "none; all input sets and bounds are explicit",
        "algorithm": "CCW corner equalities, deterministic propagation, no assignment search/backtracking",
        "right_branch_template": branch_right("1", "2", "3"),
        "partial_triangle": asdict(audit_line_names(triangle, good)),
        "triangle_conflict": asdict(audit_line_names(triangle, bad)),
        "five_symbol_witness": asdict(five_result),
        "global_rename_example": canonical_line_names((("red", "blue"), ("blue", "red"))),
        "bounded_independent_checks": bounded_checks(),
        "limitations": ["connected plane topology only", "no palette bound or unknown-name selection",
                        "no incremental editing implementation", "witnesses are valid, not proved shortest"],
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"passed": True, "input_assignments_checked": sum(
        item["input_assignments_checked"] for item in report["bounded_independent_checks"]),
        "five_symbol_witness": five_result.status}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
